### ISSUE TITLE
[FE] Post -> Series 추가 로직 구현

### ISSUE THREAD

**Issue by HJeong1200** [codestates-seb/seb41_main_009#166]

**Comment by bakjonghyo52** [comment]
1. series List 목록 제목만 나오게 
2. sereis List Gird 10칸 짜리 만들어 내기 
3. 작은 series LIst Card 하나 만들기
4. add Series 로직 구현 
5. add Series 디자인 구현

**Comment by bakjonghyo52** [comment]
index 기능 구현 필요 
사진 render 기능 추가 필요
